# Configuração do Servidor
server.port=8080

# Forçar o uso do driver PostgreSQL para conexões PostgreSQL no Render
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração da Base de Dados (Lida automaticamente pelas variáveis do Render)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
